config/routes.rb
Tasklist::Application.routes.draw do
  root :to => 'groups#index', :constraints => lambda {|r| r.env["warden"].authenticate? }
  root :to => 'home#index'
  
  get "/" => 'groups#index', :as => "user_root"
  post "/pusher/auth" => 'pusher#auth', :format => :js
  
  devise_for :users
  resources :users, :only => :show do
    collection do
      get :search
    end
  end
  
  resources :groups, :only => [:index, :show] do
    member do
      put :insert_at
    end
    
    resources :lists, :only => [:index, :create, :destroy] do
      member do
        put :share, :update, :insert_at
        get :index
      end

      resources :tasks, :only => [:create, :destroy] do
        member do
          put :toggle_close, :toggle_important, :insert_at, :update
        end
      end
    end
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :user_ids
  
  has_many :list_associations
  has_many :users, :through => :list_associations
  has_one :owner, :through => :list_associations, :source => :user, :conditions => ["list_associations.role = ?", "owner"]
  has_many :collaborators, :through => :list_associations, :source => :user, :conditions => ["list_associations.role = ?", "collaborator"]
  
  has_many :group_associations, :order => "position DESC"
  has_many :groups, :through => :group_associations
  
  has_many :tasks, :order => "closed ASC, position DESC"
  
  validates_presence_of :name
  
  class << self
    def latest
      order(:created_at.desc)
    end
  end
  
  def channel
    Pusher["private-list-#{id}"]
  end
  
  def can_access_channel(channel_name)
    case channel_name
    when /^(?:presence|private)-list-(\d+)/ then $1 == id.to_s
    else false
    end
  end
end

# == Schema Info
#
# Table name: lists
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_groups
  before_filter :load_group
  before_filter :load_lists
  before_filter :load_list, :only => [:index, :update, :destroy, :share, :insert_at], :if => @lists
  
  respond_to :html, :only => [:index]
  respond_to :js, :except => [:index]
  
  def index
    respond_with @lists = @lists.latest
  end
  
  def create
    @list = @lists.create(:name => params[:list][:name])
  end
  
  def update
    @list.update_attributes(params[:list])
  end
  
  def destroy
    @list.destroy
  end
  
  def share
    @user = User.find(params[:username])
    @list.share(@user)
  end
  
  def insert_at
    @list.group_associations.where(:group_id => @group.id).first.insert_at params[:position]
  end
    
  private
  
  def load_groups
    @groups = current_user.groups
  end
  
  def load_group
    @group = @groups.find(params[:group_id])
  end
  
  def load_lists
    @lists = @group.lists
  end
  
  def load_list
    @list = @lists.find(params[:id])
  end
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/lists/_form.html.haml
= form_for group.lists.new, :url => group_lists_path(group), :remote => true do |f|
  = f.text_field :name, :placeholder => "Create a list"
  = f.submit

app/views/lists/_group_lists.html.haml
%ol#lists
  - group.lists.each do |list| 
    = render "group_lists_list_item", :group => group, :list => list, :selected => list == current_list

app/views/lists/_group_lists_list_item.html.haml
%li{"data-id" => list.id, "data-reorder-path" => insert_at_group_list_path(group, list), :class => (selected ? "selected" : nil) }
  - if list.tasks.count > 0
    %div.counter= list.tasks.open.count
  = link_to list.name, group_list_path(group, list)

app/views/lists/_list.html.haml
%li.item{ :class => "#{selected_class(list, params[:list_id])}", "data-id" => list.id }
  - if list.tasks.count > 0
    %div.counter= list.tasks.open.count
  = link_to list.name, group_list_path(group, list)

app/views/lists/_no_list.html.haml
Create a list

app/views/lists/_sharing_user.html.haml
%li
  %p= gravatar_image_tag user.email, :align => :left, :gravatar => { :size => 24 }
  %p= user.username

app/views/lists/index.html.haml
%div#sidebar
  %div.header Lists
  = render "group_lists", :group => @group, :current_list => @list
  %div.footer
    = render 'form', :group => @group
%div#workspace
  - if @list
    = render "tasks/list", :group => @group, :list => @list
  - else
    = render "no_list"