config/routes.rb
Tasklist::Application.routes.draw do
  root :to => 'groups#index', :constraints => lambda {|r| r.env["warden"].authenticate? }
  root :to => 'home#index'
  
  get "/" => 'groups#index', :as => "user_root"
  post "/pusher/auth" => 'pusher#auth', :format => :js
  
  devise_for :users
  resources :users, :only => :show do
    collection do
      get :search
    end
  end
  
  resources :groups, :only => [:index, :show] do
    member do
      put :insert_at
    end
    
    resources :lists, :only => [:index, :create, :destroy] do
      member do
        put :share, :update, :insert_at
        get :index
      end

      resources :tasks, :only => [:create, :destroy] do
        member do
          put :toggle_close, :toggle_important, :insert_at, :update
        end
      end
    end
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  
  validates_presence_of :title
  
  acts_as_list :scope => :list
  
  named_scope :all_for_group, lambda{|group|{
    :joins      => {:list, :group_associations},
    :conditions => {:group_associations => {:group_id => group.id}},
    :select     => "tasks.*, lists.id" }
  }
  
  class << self
    def ordered
      all
    end
    
    def open
      where(:closed => false)
    end
    
    def closed
      where(:closed => true)
    end
    
    def important
      where(:important => true)
    end
  end
  
  def toggle_close
    update_attribute :closed, !closed
  end
  
  def toggle_important
    update_attribute :important, !important
  end
end

# == Schema Info
#
# Table name: tasks
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  closed     :boolean
#  position   :integer
#  list_id    :integer
#  created_at :datetime
#  updated_at :datetime

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :load_group
  before_filter :load_list
  before_filter :load_task, :only => [:toggle_close, :toggle_important, :destroy, :insert_at, :update]  
  
  respond_to :js
  
  def create
    @task = @list.tasks.create :title => params[:task][:title]
  end
  
  def update
    @task.update_attributes params[:task]
  end
  
  def toggle_close
    @task.toggle_close
  end
  
  def toggle_important
    @task.toggle_important
  end
  
  def destroy
    @task.destroy
  end
  
  def insert_at
    @task.insert_at params[:position]
  end
  
  private
  
  def load_group
    @group = current_user.groups.find(params[:group_id])
  end
  
  def load_list
    @list = @group.lists.find(params[:list_id])
  end
  
  def load_task
    @task = @list.tasks.find(params[:id])
  end
end

app/helpers/task_helper.rb
module TaskHelper
  def closed_class(task)
    task.closed? ? "closed" : nil
  end
end

app/views/tasks/_form.html.haml
= form_for Task.new, :url => group_list_tasks_path(group, list), :remote => true do |f|
  = f.text_field :title, :id => nil, :class => "new_task", :autocomplete => "off", :placeholder => "Create a task"

app/views/tasks/_list.html.haml
%div#list
  %div.header
    %div.left
      %div
        Incomplete
    %div.delete
      = link_to group_list_path(group, list), :remote => true, :method => :delete do
        Delete
  %div{ :class => "new-task" }
    = render "tasks/form", :group => group, :list => list
  %ol#tasks{ "data-list-id" => list.id }
    = render list.tasks.open.ordered, :group => group, :list => list
  %ul#closed-tasks{ "data-list-id" => list.id }
    = render list.tasks.closed.ordered, :group => group, :list => list

app/views/tasks/_sharing_form.html.haml
= form_tag share_list_path(list), :class => :share_list, :remote => true, :method => :put do
  = hidden_field_tag "username", nil, :id => nil, :class => "username"
  = text_field_tag nil, nil, :id => nil, :class => "ac_username"
  = submit_tag "add"
%ul.share_users
  - list.collaborators.order(:name.asc).reject{|u| u.id == current_user.id }.each do |u|
    = render "sharing_user", :user => u
%a.share_close{ :href => "javascript:;" } Close

app/views/tasks/_task.html.haml
%li.task{ "data-id" => task.id, "data-path" => group_list_task_path(group, list, task), "data-task" => task.title,
     "data-reorder-path" => insert_at_group_list_task_path(group, list, task), :class => "#{closed_class(task)}"}
  %div{ :class => "checkbox #{closed_class(task)}" }
    = link_to toggle_close_group_list_task_path(group, list, task), :remote => true, :method => :put do
      Complete
  %div.star{ :class => (task.important? ? "starred" : nil) }
    = link_to toggle_important_group_list_task_path(group, list, task), :remote => true, :method => :put do
      Star
  %div.delete
    = link_to group_list_task_path(group, list, task), :remote => true, :method => :delete do
      Delete
  %div.project-title
  %div.preview
    %div.title 
      = auto_link(task.title, :html => { :target => '_blank' }) do |text|
        - text.sub(%r(^http://(www\.)?), "")

app/views/tasks/complete.js.erb
$(document).trigger({type:'tasks:complete',taskId:"<%= @task.id %>",taskHtml:"<%=raw escape_javascript(render @task) %>"});